title: Yuhang wandering in the world
description: > # this means to ignore newlines until "baseurl:"
  I love this world.
permalink: ':title/'
baseurl:  # the subpath of your site, e.g. /blog
#url: https://longyintheworld.github.io/wandering # the base hostname & protocol for your site, e.g. http://example.com
url: ""
#<div><center>Cartographer </center><center>Wanderluster</center><center>Bookworm</center><center>Shutterbug</center><center>Gymaholic</center></div>
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Yuhang # add your name
author-img: yuhang.jpg # add your photo
about-author: <div><center>Cartographer</center><center>Wanderluster</center><center>Bookworm</center><center>Shutterbug</center><center>Gymaholic</center></div> # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: YuhangGu # add your Github handle
instagram: gu_yuhang
linkedin: # add your Linkedin 
weibo: u/2234197177?profile_ftype=1&is_all=1#_0
email: gu_yuhang@outlook.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
